import AppLayout from "@Components/Layout/AppLayout";
import Head from "next/head";
import type { NextPage } from "next";
import React from "react";
import RecentBlock from "@Components/RecentBlock";
import SupplyStats from "@Components/SupplyStats";
import Toasts from "@Components/Toasts";
import Transactions from "@Components/Transactions";
import { request } from "@Pages/api/handler";
import styles from "@Styles/Home.module.css";

const Home: NextPage = () => {
  const getSignerList = async () => {
    const result = await request.getSignerList();
    return result;
  };

  React.useEffect(() => {
    getSignerList().then((res: any) => {
      localStorage.setItem("signers", JSON.stringify(res?.data));
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home - GoChain Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <div className="container py-4">
          <Toasts />
          <div className="row align-items-stretch">
            <div className="col-lg-6 col-xs-12">
              <SupplyStats />
            </div>
            <div className="col-lg-6 col-xs-12 mt-4 mt-lg-0">
              <Transactions />
            </div>
          </div>
          <RecentBlock />
        </div>
      </AppLayout>
    </div>
  );
};

export default Home;
