import AppLayout from "@Components/Layout/AppLayout";
import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import styles from "@Styles/Home.module.css";

const Signers: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Signers - GoChain Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
      <div className="container">
  <div className="card">
    <div className="card-body">
      <div className="card-title">
        <img src="/assets/icons/check-square.svg" alt="Signers" />
        SIGNERS
      </div>
      {/* <app-tabs name="signers_tab" *ngIf="statsData"> */}
        <tab
            // *ngFor="let stat of statsData; let rangeIndex=index"
            // [name]="stat.range"
            // [title]="stat.range"
        >
          {/* <tab-content> */}
            {/* <h6 className="text-uppercase text-primary text-center mb-1">{{stat.range}}</h6> */}
            <div className="chart mb-1">
              {/* <ngx-charts-pie-chart
                  [labels]="true"
                  [doughnut]="true"
                  [gradient]="true"
                  [trimLabels]="true"
                  [arcWidth]="0.618"
                  [scheme]="colorScheme"
                  [results]="stat.chartData"
                  (activate)="onChartItemEnter($event, rangeIndex)"
                  (deactivate)="onChartItemLeave()"
              >
              </ngx-charts-pie-chart> */}
            </div>
            <div className="my-1">
              <p>
                {/* Block signers for {{stat.block_range.end_block - stat.block_range.start_block}} blocks from */}
                {/* <a routerLink="/blocks/{{stat.block_range.start_block}}">#{{stat.block_range.start_block}}</a> to <a */}
                  {/* routerLink="/blocks/{{stat.block_range.end_block}}">#{{stat.block_range.end_block}}</a>. */}
              </p>
            </div>
            {/* <ng-container *appViewportSize="['small']"> */}
              <div className="data-list">
                {/* <div className="data-list-item" *ngFor="let item of stat.signer_stats"> */}
                <div className="data-list-item">
                  <div className="data-list-row">
                    <div className="data-list-term">
                      Account
                    </div>
                    <div className="data-list-desc text-monospace">
                      {/* <a routerLink="/addr/{{item.signer_address}}">{{item.signer_address}}</a> */}
                    </div>
                  </div>
                  {/* <ng-container *ngIf="item.data"> */}
                    <div className="data-list-row">
                      <div className="data-list-term">
                        Name
                      </div>
                      <div className="data-list-desc">
                        {/* {{item?.data?.name}} */}
                      </div>
                    </div>
                    <div className="data-list-row">
                      <div className="data-list-term">
                        Region
                      </div>
                      <div className="data-list-desc">
                        {/* {{item?.data?.region}} */}
                      </div>
                    </div>
                    <div className="data-list-row">
                      <div className="data-list-term">
                        URL
                      </div>
                      <div className="data-list-desc">
                        {/* <a href="{{item?.data?.url}}" target="_blank">{{item?.data?.url}}</a> */}
                      </div>
                    </div>
                  {/* </ng-container> */}
                  <div className="data-list-row">
                    <div className="data-list-term">
                      Blocks
                    </div>
                    <div className="data-list-desc">
                      {/* {{item?.blocks_count}} */}
                    </div>
                  </div>
                  <div className="data-list-row">
                    <div className="data-list-term">
                      Percent
                    </div>
                    <div className="data-list-desc">
                      {/* {{item?.percent}} */}
                    </div>
                  </div>
                </div>
              </div>
            {/* </ng-container> */}
            {/* <ng-container *appViewportSize="['medium', 'large']"> */}
              <div>
                <div className="table-responsive">
                  {/* <table className="table table-bordered" [svData]="stat.signer_stats" #sv="svDataTable"> */}
                  <table className="table table-bordered">
                    <thead>
                    <tr>
                      <th>
                        <sv-default-sorter by="data.signer_address">Account</sv-default-sorter>
                      </th>
                      <th>
                        <sv-default-sorter by="data.name">Name</sv-default-sorter>
                      </th>
                      <th>
                        <sv-default-sorter by="data.region">Region</sv-default-sorter>
                      </th>
                      <th>
                        <sv-default-sorter by="data.url">URL</sv-default-sorter>
                      </th>
                      <th className="text-right">
                        <sv-default-sorter by="blocks_count">Blocks</sv-default-sorter>
                      </th>
                      <th className="text-right">
                        <sv-default-sorter by="percent">%</sv-default-sorter>
                      </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr
                        // *ngFor="let item of sv.data; let itemIndex = index;"
                        // [ngclassName]="{'table-active': this.hoveredItem && this.hoveredItem.rangeIndex === rangeIndex && this.hoveredItem.itemIndex === itemIndex}"
                    >
                      <td className="text-monospace">
                        {/* <a routerLink="/addr/{{item.signer_address}}">{{item.signer_address}}</a> */}
                      </td>
                      {/* <td>{{item?.data?.name}}</td> */}
                      {/* <td>{{item?.data?.region}}</td> */}
                      <td>
                        {/* <a href="{{item?.data?.url}}" target="_blank">{{item?.data?.url}}</a> */}
                      </td>
                      {/* <td>{{item?.blocks_count}}</td> */}
                      {/* <td>{{item?.percent}}</td> */}
                    </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            {/* </ng-container> */}
          {/* </tab-content> */}
        </tab>
      {/* </app-tabs> */}
    </div>
  </div>
</div>

      </AppLayout>
    </div>
  );
};

export default Signers;
