import { useDispatch, useSelector } from "react-redux";

import AppLayout from "@Components/Layout/AppLayout";
import ControlledTabs from "@Components/Tabs";
import Head from "next/head";
import Loading from "@Components/Loading";
import type { NextPage } from "next";
import React from "react";
import { getSignerStats } from "@Redux/actions/signers";
import styles from "@Styles/Home.module.css";

const Signers: NextPage = () => {
  const dispatch = useDispatch();
  const { isLoading } = useSelector((state: any) => state.signer) || {};

  React.useEffect(() => {
    dispatch(getSignerStats());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Signers - GoChain Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <div className="container">
          {isLoading ? (
            <Loading />
          ) : (
            <div className="card">
              <div className="card-body">
                <div className="card-title">
                  <img src="/assets/icons/check-square.svg" alt="Signers" />
                  SIGNERS
                </div>
                <ControlledTabs isSigner={true} />
              </div>
            </div>
          )}
        </div>
      </AppLayout>
    </div>
  );
};

export default Signers;
