import AppLayout from "@Components/Layout/AppLayout";
import Head from "next/head";
import type { NextPage } from "next";
import styles from "@Styles/Home.module.css";

const WalletAccount: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wallet - GoChain Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
          <h1 className={styles.title}>
            Account
          </h1>

          
      </AppLayout>
    </div>
  );
};

export default WalletAccount;
