import AppLayout from "@Components/Layout/AppLayout";
import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import styles from "@Styles/Home.module.css";

const Wallet: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wallet - GoChain Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <div className="container">
          <div className="card f-h">
            <div className="card-body">
              <div className="row justify-content-center h-100 mt-5">
                <div className="col-md-6">
                  <h4 className="text-center text-primary text-uppercase">
                    Please enter your private key to proceed
                  </h4>
                  <form
                    className="mt-4"
                    // [formGroup]="privateKeyForm"
                    // (submit)="onPrivateKeySubmit()"
                  >
                    <div className="input-group">
                      <input
                        // [type]="passwordField.type"
                        className="form-control"
                        placeholder="Private Key"
                        formControlName="privateKey"
                        autoFocus
                        required
                        // [readOnly]="walletService.isProcessing"
                      />
                      <div className="input-group-append">
                        <button
                          className="btn btn-outline-secondary"
                          type="button"
                          // (click)="passwordField.toggle()"
                        >
                          <img
                            src="/assets/icons/{{passwordField.icon}}"
                            height="14px"
                            // [alt]="passwordField.alt"
                          />
                        </button>
                      </div>
                    </div>
                    <button
                      type="submit"
                      className="btn btn-primary btn-block mt-4"
                      // [disabled]="walletService.isProcessing"
                    >
                      {/* <ng-container *ngIf="walletService.isProcessing; else open"> */}
                      OPENING{" "}
                      <img src="/assets/icons/loader.svg" alt="Opening" />
                      {/* </ng-container> */}
                      {/* <ng-template #open> */}
                      OPEN WALLET
                      {/* </ng-template> */}
                    </button>
                  </form>
                  <div className="row mt-4">
                    <div className="col-12">
                      <button
                        // routerLink="create"
                        type="button"
                        className="btn btn-outline-primary btn-block"
                        // [disabled]="walletService.isProcessing"
                      >
                        <a href="/wallet/create">Create Account</a>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </AppLayout>
    </div>
  );
};

export default Wallet;
